### ISSUE TITLE
Handle failed authentication exceptions

### ISSUE THREAD

**Issue by viktorKhan** [lucoenergia/conluz#22]
## Missing token
When making a call with a missing token when the endpoint requires authentication the fail is finally captured by the class `org.springframework.security.web.authentication.Http403ForbiddenEntryPoint` which returns a 403 error.

## Expired token
When making a call with an expired token, the application returns a 403 error with an empty body:

![imagen](https://github.com/lucoenergia/conluz/assets/4686378/ac47af2c-cec8-4d96-8561-cdb8ff73aa41)

This is the exception thrown:
```
2024-01-03T11:50:16.183+01:00 ERROR 34922 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

io.jsonwebtoken.ExpiredJwtException: JWT expired at 2023-12-15T18:37:51Z. Current time: 2024-01-03T10:50:16Z, a difference of 1613545177 milliseconds.  Allowed clock skew: 0 milliseconds.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:427) ~[jjwt-impl-0.11.5.jar:0.11.5]
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:529) ~[jjwt-impl-0.11.5.jar:0.11.5]
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:589) ~[jjwt-impl-0.11.5.jar:0.11.5]
	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173) ~[jjwt-impl-0.11.5.jar:0.11.5]
	at org.lucoenergia.conluz.infrastructure.shared.security.auth.JwtAuthRepository.getAllClaims(JwtAuthRepository.java:96) ~[main/:na]
	at org.lucoenergia.conluz.infrastructure.shared.security.auth.JwtAuthRepository.getClaim(JwtAuthRepository.java:100) ~[main/:na]
	at org.lucoenergia.conluz.infrastructure.shared.security.auth.JwtAuthRepository.getUserIdFromToken(JwtAuthRepository.java:58) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
```

We must return a 401 HTTP error code and a proper message.

**Comment by viktorKhan** [comment]
For missing token, we have created a customized entry point to replace `Http403ForbiddenEntryPoint`
