### ISSUE TITLE
Error getting Datadis consumption

### ISSUE THREAD

**Issue by viktorKhan** [lucoenergia/conluz#77]
For some reason, when trying to get Datadis consumptions from supplies we get this error:

```
12-06-2024 04:00:02.018 [scheduling-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.lucoenergia.conluz.domain.admin.supply.Supply.getDatadisIsThirdParty()" is null
	at org.lucoenergia.conluz.infrastructure.consumption.datadis.get.GetDatadisConsumptionRepositoryRest.getHourlyConsumptionsByMonth(GetDatadisConsumptionRepositoryRest.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at org.lucoenergia.conluz.infrastructure.consumption.datadis.get.GetDatadisConsumptionRepositoryRest$$SpringCGLIB$$0.getHourlyConsumptionsByMonth(<generated>)
	at org.lucoenergia.conluz.domain.consumption.datadis.sync.DatadisConsumptionSyncService.synchronizeConsumptions(DatadisConsumptionSyncService.java:74)
	at org.lucoenergia.conluz.infrastructure.consumption.datadis.sync.DatadisConsumptionsSyncDailyJob.run(DatadisConsumptionsSyncDailyJob.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by viktorKhan** [comment]
The problem is happening because, for some reason, the field `supplies.datadis_is_third_party` is set to null at some point.

**Comment by viktorKhan** [comment]
I detected the issue. The issue is happening during the process `org.lucoenergia.conluz.domain.admin.supply.sync.DatadisSuppliesSyncService#synchronizeSupplies`
As part of this process we:

- Get all supplies from DB
- Get all supplies from Datadis
- Update supplies in DB from data retrieved from Datadis.

The problem is that the process to get all supplies from DB is not getting the value of `datdisIsThirdParty` , so, when calling to update the supply with that data, the field `datdisIsThirdParty` is set to `null`.

We need to fix the mapper `SupplyEntityMapper` to map also the field `datdisIsThirdParty`.
